spring:
  application:
    name: auth-server
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_HOST:http://localhost:8761/eureka/}
server:
  port: 6700
seni-app:
  keycloak:
    admin:
      username: ${KEYCLOAK_USERNAME:admin}
      password: ${KEYCLOAK_PASSWORD:admin}
      clientId: ${KEYCLOAK_CLIENT:auth_client}
      clientSecret: ${KEYCLOAK_SECRET:NaDUCVV24i4TmQXjUrAeITMkGulyKMoN}
    realm: ${KEYCLOAK_REALM:my-realm}
    serverUrl: ${KEYCLOAK_HOST:http://localhost:1200/auth}
    authBaseUrl: ${KEYCLOAK_AUTH_URL:http://localhost:1200/realms/my-realm/protocol/openid-connect}